/**
 * @typedef {import("../config/battleConfig").LegacyEffectIdEnum} LegacyEffectIdEnum
 * @typedef {Enum<effectIdEnum>} NewEffectIdEnum
 * @typedef {LegacyEffectIdEnum | NewEffectIdEnum} EffectIdEnum
 */
const effectIdEnum = Object.freeze({
  TEST_EFFECT: "testEffect",
  ATK_UP: "atkUp",
  SHIELD: "shield",
  DEBUFF_IMMUNITY: "debuffImmunity",
  AQUA_BLESSING: "aquaBlessing",
  DOOM_DESIRE: "doomDesire",
});

/**
 * @typedef {import("../config/battleConfig").LegacyMoveIdEnum} LegacyMoveIdEnum
 * @typedef {Enum<moveIdEnum>} NewMoveIdEnum
 * @typedef {LegacyMoveIdEnum | NewMoveIdEnum} MoveIdEnum
 */
const moveIdEnum = Object.freeze({
  TEST_MOVE: "999",
  TEST_MOVE2: "998",
  FIRE_PUNCH: "m7",
  ICE_PUNCH: "m8",
  VINE_WHIP: "m22",
  CONFUSION: "m93",
  PSYCHIC: "m94",
  ICY_WIND: "m196",
  BRICK_BREAK: "m280",
  FEATHER_DANCE: "m297",
  DOOM_DESIRE: "m353",
  NIGHT_SLASH: "m400",
  IRON_HEAD: "m442",
  BUG_BITE: "m450",
  WOOD_HAMMER: "m452",
  QUASH: "m511",
  ICICLE_CRASH: "m556",
  AQUA_IMPACT: "m618-1",
  MAGMA_IMPACT: "m619-1",
  FLAME_BALL: "m780-1",
});

/**
 * @typedef {import("../config/battleConfig").LegacyAbilityIdEnum} LegacyAbilityIdEnum
 * @typedef {Enum<abilityIdEnum>} NewAbilityIdEnum
 * @typedef {LegacyAbilityIdEnum | NewAbilityIdEnum} AbilityIdEnum
 */
const abilityIdEnum = Object.freeze({
  STENCH: "1",
  DRIZZLE: "2",
  SPEED_BOOST: "3",
  BATTLE_ARMOR: "4",
  STURDY: "5",
  DAMP: "6",
  LIMBER: "7",
  SAND_VEIL: "8",
  STATIC: "9",
  VOLT_ABSORB: "10",
  WATER_ABSORB: "11",
  OBLIVIOUS: "12",
  CLOUD_NINE: "13",
  COMPOUND_EYES: "14",
  INSOMNIA: "15",
  COLOR_CHANGE: "16",
  IMMUNITY: "17",
  FLASH_FIRE: "18",
  SHIELD_DUST: "19",
  OWN_TEMPO: "20",
  SUCTION_CUPS: "21",
  INTIMIDATE: "22",
  SHADOW_TAG: "23",
  ROUGH_SKIN: "24",
  WONDER_GUARD: "25",
  LEVITATE: "26",
  EFFECT_SPORE: "27",
  SYNCHRONIZE: "28",
  CLEAR_BODY: "29",
  NATURAL_CURE: "30",
  LIGHTNING_ROD: "31",
  SERENE_GRACE: "32",
  SWIFT_SWIM: "33",
  CHLOROPHYLL: "34",
  ILLUMINATE: "35",
  TRACE: "36",
  HUGE_POWER: "37",
  POISON_POINT: "38",
  INNER_FOCUS: "39",
  MAGMA_ARMOR: "40",
  WATER_VEIL: "41",
  MAGNET_PULL: "42",
  SOUNDPROOF: "43",
  RAIN_DISH: "44",
  SAND_STREAM: "45",
  PRESSURE: "46",
  THICK_FAT: "47",
  EARLY_BIRD: "48",
  FLAME_BODY: "49",
  RUN_AWAY: "50",
  KEEN_EYE: "51",
  HYPER_CUTTER: "52",
  PICKUP: "53",
  TRUANT: "54",
  HUSTLE: "55",
  CUTE_CHARM: "56",
  PLUS: "57",
  MINUS: "58",
  FORECAST: "59",
  STICKY_HOLD: "60",
  SHED_SKIN: "61",
  GUTS: "62",
  MARVEL_SCALE: "63",
  LIQUID_OOZE: "64",
  OVERGROW: "65",
  BLAZE: "66",
  TORRENT: "67",
  SWARM: "68",
  ROCK_HEAD: "69",
  DROUGHT: "70",
  ARENA_TRAP: "71",
  VITAL_SPIRIT: "72",
  WHITE_SMOKE: "73",
  PURE_POWER: "74",
  SHELL_ARMOR: "75",
  AIR_LOCK: "76",
  TANGLED_FEET: "77",
  MOTOR_DRIVE: "78",
  RIVALRY: "79",
  STEADFAST: "80",
  SNOW_CLOAK: "81",
  GLUTTONY: "82",
  ANGER_POINT: "83",
  UNBURDEN: "84",
  HEATPROOF: "85",
  SIMPLE: "86",
  DRY_SKIN: "87",
  DOWNLOAD: "88",
  IRON_FIST: "89",
  POISON_HEAL: "90",
  ADAPTABILITY: "91",
  SKILL_LINK: "92",
  HYDRATION: "93",
  SOLAR_POWER: "94",
  QUICK_FEET: "95",
  NORMALIZE: "96",
  SNIPER: "97",
  MAGIC_GUARD: "98",
  NO_GUARD: "99",
  STALL: "100",
  TECHNICIAN: "101",
  LEAF_GUARD: "102",
  KLUTZ: "103",
  MOLD_BREAKER: "104",
  SUPER_LUCK: "105",
  AFTERMATH: "106",
  ANTICIPATION: "107",
  FOREWARN: "108",
  UNAWARE: "109",
  TINTED_LENS: "110",
  FILTER: "111",
  SLOW_START: "112",
  SCRAPPY: "113",
  STORM_DRAIN: "114",
  ICE_BODY: "115",
  SOLID_ROCK: "116",
  SNOW_WARNING: "117",
  HONEY_GATHER: "118",
  FRISK: "119",
  RECKLESS: "120",
  MULTITYPE: "121",
  FLOWER_GIFT: "122",
  BAD_DREAMS: "123",
  PICKPOCKET: "124",
  SHEER_FORCE: "125",
  CONTRARY: "126",
  UNNERVE: "127",
  DEFIANT: "128",
  DEFEATIST: "129",
  CURSED_BODY: "130",
  HEALER: "131",
  FRIEND_GUARD: "132",
  WEAK_ARMOR: "133",
  HEAVY_METAL: "134",
  LIGHT_METAL: "135",
  MULTISCALE: "136",
  TOXIC_BOOST: "137",
  FLARE_BOOST: "138",
  HARVEST: "139",
  TELEPATHY: "140",
  MOODY: "141",
  OVERCOAT: "142",
  POISON_TOUCH: "143",
  REGENERATOR: "144",
  BIG_PECKS: "145",
  SAND_RUSH: "146",
  WONDER_SKIN: "147",
  ANALYTIC: "148",
  ILLUSION: "149",
  IMPOSTER: "150",
  INFILTRATOR: "151",
  MUMMY: "152",
  MOXIE: "153",
  JUSTIFIED: "154",
  RATTLED: "155",
  MAGIC_BOUNCE: "156",
  SAP_SIPPER: "157",
  PRANKSTER: "158",
  SAND_FORCE: "159",
  IRON_BARBS: "160",
  ZEN_MODE: "161",
  VICTORY_STAR: "162",
  TURBOBLAZE: "163",
  TERAVOLT: "164",
  AROMA_VEIL: "165",
  FLOWER_VEIL: "166",
  CHEEK_POUCH: "167",
  PROTEAN: "168",
  FUR_COAT: "169",
  MAGICIAN: "170",
  BULLETPROOF: "171",
  COMPETITIVE: "172",
  STRONG_JAW: "173",
  REFRIGERATE: "174",
  SWEET_VEIL: "175",
  STANCE_CHANGE: "176",
  GALE_WINGS: "177",
  MEGA_LAUNCHER: "178",
  GRASS_PELT: "179",
  SYMBIOSIS: "180",
  TOUGH_CLAWS: "181",
  PIXILATE: "182",
  GOOEY: "183",
  AERILATE: "184",
  PARENTAL_BOND: "185",
  DARK_AURA: "186",
  FAIRY_AURA: "187",
  AURA_BREAK: "188",
  PRIMORDIAL_SEA: "189",
  DESOLATE_LAND: "190",
  DELTA_STREAM: "191",
  STAMINA: "192",
  WIMP_OUT: "193",
  EMERGENCY_EXIT: "194",
  WATER_COMPACTION: "195",
  MERCILESS: "196",
  SHIELDS_DOWN: "197",
  STAKEOUT: "198",
  WATER_BUBBLE: "199",
  STEELWORKER: "200",
  BERSERK: "201",
  SLUSH_RUSH: "202",
  LONG_REACH: "203",
  LIQUID_VOICE: "204",
  TRIAGE: "205",
  GALVANIZE: "206",
  SURGE_SURFER: "207",
  SCHOOLING: "208",
  DISGUISE: "209",
  BATTLE_BOND: "210",
  POWER_CONSTRUCT: "211",
  CORROSION: "212",
  COMATOSE: "213",
  QUEENLY_MAJESTY: "214",
  INNARDS_OUT: "215",
  DANCER: "216",
  BATTERY: "217",
  FLUFFY: "218",
  DAZZLING: "219",
  SOUL_HEART: "220",
  TANGLING_HAIR: "221",
  RECEIVER: "222",
  POWER_OF_ALCHEMY: "223",
  BEAST_BOOST: "224",
  RKS_SYSTEM: "225",
  ELECTRIC_SURGE: "226",
  PSYCHIC_SURGE: "227",
  MISTY_SURGE: "228",
  GRASSY_SURGE: "229",
  FULL_METAL_BODY: "230",
  SHADOW_SHIELD: "231",
  PRISM_ARMOR: "232",
  NEUROFORCE: "233",
  INTREPID_SWORD: "234",
  DAUNTLESS_SHIELD: "235",
  LIBERO: "236",
  BALL_FETCH: "237",
  COTTON_DOWN: "238",
  PROPELLER_TAIL: "239",
  MIRROR_ARMOR: "240",
  GULP_MISSILE: "241",
  STALWART: "242",
  STEAM_ENGINE: "243",
  PUNK_ROCK: "244",
  SAND_SPIT: "245",
  ICE_SCALES: "246",
  RIPEN: "247",
  ICE_FACE: "248",
  POWER_SPOT: "249",
  MIMICRY: "250",
  SCREEN_CLEANER: "251",
  STEELY_SPIRIT: "252",
  PERISH_BODY: "253",
  WANDERING_SPIRIT: "254",
  GORILLA_TACTICS: "255",
  NEUTRALIZING_GAS: "256",
  PASTEL_VEIL: "257",
  HUNGER_SWITCH: "258",
  QUICK_DRAW: "259",
  UNSEEN_FIST: "260",
  CURIOUS_MEDICINE: "261",
  TRANSISTOR: "262",
  DRAGONS_MAW: "263",
  CHILLING_NEIGH: "264",
  GRIM_NEIGH: "265",
  AS_ONE_GLASTRIER: "266",
  AS_ONE_SPECTRIER: "267",
  LINGERING_AROMA: "268",
  SEED_SOWER: "269",
  THERMAL_EXCHANGE: "270",
  ANGER_SHELL: "271",
  PURIFYING_SALT: "272",
  WELL_BAKED_BODY: "273",
  WIND_RIDER: "274",
  GUARD_DOG: "275",
  ROCKY_PAYLOAD: "276",
  WIND_POWER: "277",
  ZERO_TO_HERO: "278",
  COMMANDER: "279",
  ELECTROMORPHOSIS: "280",
  PROTOSYNTHESIS: "281",
  QUARK_DRIVE: "282",
  GOOD_AS_GOLD: "283",
  VESSEL_OF_RUIN: "284",
  SWORD_OF_RUIN: "285",
  TABLETS_OF_RUIN: "286",
  BEADS_OF_RUIN: "287",
  ORICHALCUM_PULSE: "288",
  HADRON_ENGINE: "289",
  OPPORTUNIST: "290",
  CUD_CHEW: "291",
  SHARPNESS: "292",
  SUPREME_OVERLORD: "293",
  COSTAR: "294",
  TOXIC_DEBRIS: "295",
  ARMOR_TAIL: "296",
  EARTH_EATER: "297",
  MYCELIUM_MIGHT: "298",
  MINDS_EYE: "299",
  SUPERSWEET_SYRUP: "300",
  HOSPITALITY: "301",
  TOXIC_CHAIN: "302",
  EMBODY_ASPECT: "303",
  TERA_SHIFT: "304",
  TERA_SHELL: "305",
  TERAFORM_ZERO: "306",
  POISON_PUPPETEER: "307",
  MOUNTAINEER: "10001",
  WAVE_RIDER: "10002",
  SKATER: "10003",
  THRUST: "10004",
  PERCEPTION: "10005",
  PARRY: "10006",
  INSTINCT: "10007",
  DODGE: "10008",
  JAGGED_EDGE: "10009",
  FROSTBITE: "10010",
  TENACITY: "10011",
  PRIDE: "10012",
  DEEP_SLEEP: "10013",
  POWER_NAP: "10014",
  SPIRIT: "10015",
  WARM_BLANKET: "10016",
  GULP: "10017",
  HERBIVORE: "10018",
  SANDPIT: "10019",
  HOT_BLOODED: "10020",
  MEDIC: "10021",
  LIFE_FORCE: "10022",
  LUNCHBOX: "10023",
  NURSE: "10024",
  MELEE: "10025",
  SPONGE: "10026",
  BODYGUARD: "10027",
  HERO: "10028",
  LAST_BASTION: "10029",
  STEALTH: "10030",
  VANGUARD: "10031",
  NOMAD: "10032",
  SEQUENCE: "10033",
  GRASS_CLOAK: "10034",
  CELEBRATE: "10035",
  LULLABY: "10036",
  CALMING: "10037",
  DAZE: "10038",
  FRIGHTEN: "10039",
  INTERFERENCE: "10040",
  MOOD_MAKER: "10041",
  CONFIDENCE: "10042",
  FORTUNE: "10043",
  BONANZA: "10044",
  EXPLODE: "10045",
  OMNIPOTENT: "10046",
  SHARE: "10047",
  BLACK_HOLE: "10048",
  SHADOW_DASH: "10049",
  SPRINT: "10050",
  DISGUST: "10051",
  HIGH_RISE: "10052",
  CLIMBER: "10053",
  FLAME_BOOST: "10054",
  AQUA_BOOST: "10055",
  RUN_UP: "10056",
  CONQUEROR: "10057",
  SHACKLE: "10058",
  DECOY: "10059",
  SHIELD: "10060",
  AQUA_POWER: "2-1",
  MAGMA_POWER: "70-1",
  BURNING_DRAFT: "20018",
  JET_SPEED: "20019",
  ALPHA_CORE: "20020",
  OMEGA_CORE: "20021",
});

/** @typedef {Enum<heldItemIdEnum>} HeldItemIdEnum */
const heldItemIdEnum = Object.freeze({
  LUM_BERRY: "h134",
  SITRUS_BERRY: "h135",
  EXP_SHARE: "h193",
  CHOICE_BAND: "h197",
  AMULET_COIN: "h200",
  FOCUS_BAND: "h207",
  LUCKY_EGG: "h208",
  LEFTOVERS: "h211",
  WIDE_LENS: "h242",
  LIFE_ORB: "h247",
  POWER_HERB: "h248",
  FOCUS_SASH: "h252",
  CHOICE_SCARF: "h264",
  CHOICE_SPECS: "h274",
  EVIOLITE: "h581",
  HEAVY_DUTY_BOOTS: "h1178",
});

/** @typedef {Enum<battleEventEnum>} BattleEventEnum */
const battleEventEnum = Object.freeze({
  BATTLE_BEGIN: "battleStart",
  TURN_END: "turnEnd",
  TURN_BEGIN: "turnBegin",
  BEFORE_MOVE: "beforeMove",
  BEFORE_MOVE_EXECUTE: "beforeMoveExecute",
  AFTER_MOVE: "afterMove",
  BEFORE_DAMAGE_DEALT: "beforeDamageDealt",
  AFTER_DAMAGE_DEALT: "afterDamageDealt",
  BEFORE_DAMAGE_TAKEN: "beforeDamageTaken",
  AFTER_DAMAGE_TAKEN: "afterDamageTaken",
  BEFORE_CR_GAINED: "beforeCRGained",
  AFTER_CR_GAINED: "afterCRGained",
  BEFORE_EFFECT_ADD: "beforeEffectAdd",
  AFTER_EFFECT_ADD: "afterEffectAdd",
  BEFORE_EFFECT_REMOVE: "beforeEffectRemove",
  AFTER_EFFECT_REMOVE: "afterEffectRemove",
  BEFORE_STATUS_APPLY: "beforeStatusApply",
  AFTER_STATUS_APPLY: "afterStatusApply",
  BEFORE_CAUSE_FAINT: "beforeCauseFaint",
  BEFORE_FAINT: "beforeFaint",
  AFTER_FAINT: "afterFaint",
  CALCULATE_TYPE_MULTIPLIER: "calculateTypeMultiplier",
  CALCULATE_MISS: "calculateMiss",
  GET_ELIGIBLE_TARGETS: "getEligibleTargets",
  AFTER_WEATHER_SET: "afterWeatherSet",
  AFTER_TRANSFORM: "afterTransform",
});

/**
 * @template {BattleEventEnum} K
 * @typedef {{
 *  [battleEventEnum.BATTLE_BEGIN]: {},
 *  [battleEventEnum.TURN_END]: { activePokemon: BattlePokemon },
 *  [battleEventEnum.TURN_BEGIN]: {},
 *  [battleEventEnum.BEFORE_MOVE]: { canUseMove: boolean, source: BattlePokemon, primaryTarget: BattlePokemon, moveId: MoveIdEnum} ,
 *  [battleEventEnum.BEFORE_MOVE_EXECUTE]: { source: BattlePokemon, primaryTarget: BattlePokemon, allTargets: BattlePokemon[], missedTargets: BattlePokemon[], moveId: MoveIdEnum },
 *  [battleEventEnum.AFTER_MOVE]: { source: BattlePokemon, primaryTarget: BattlePokemon, allTargets: BattlePokemon[], missedTargets: BattlePokemon[], moveId: MoveIdEnum },
 *  [battleEventEnum.BEFORE_DAMAGE_DEALT]: { target: BattlePokemon, source: BattlePokemon, damage: number, damageInfo: any },
 *  [battleEventEnum.AFTER_DAMAGE_DEALT]: any,
 *  [battleEventEnum.BEFORE_DAMAGE_TAKEN]: { target: BattlePokemon, source: BattlePokemon, damage: number, maxDamage: number, damageInfo: any },
 *  [battleEventEnum.AFTER_DAMAGE_TAKEN]: { target: BattlePokemon, source: BattlePokemon, damage: number, damageInfo: any },
 *  [battleEventEnum.BEFORE_CR_GAINED]: any,
 *  [battleEventEnum.AFTER_CR_GAINED]: any,
 *  [battleEventEnum.BEFORE_EFFECT_ADD]: { target: BattlePokemon, source: BattlePokemon, effectId: EffectIdEnum, duration: number, initialArgs: any, canAdd: boolean },
 *  [battleEventEnum.AFTER_EFFECT_ADD]: any,
 *  [battleEventEnum.BEFORE_EFFECT_REMOVE]: any,
 *  [battleEventEnum.AFTER_EFFECT_REMOVE]: any,
 *  [battleEventEnum.BEFORE_STATUS_APPLY]: any,
 *  [battleEventEnum.AFTER_STATUS_APPLY]: { target: BattlePokemon, source: BattlePokemon, statusId: StatusConditionEnum },
 *  [battleEventEnum.BEFORE_CAUSE_FAINT]: any,
 *  [battleEventEnum.BEFORE_FAINT]: any,
 *  [battleEventEnum.AFTER_FAINT]: any,
 *  [battleEventEnum.CALCULATE_TYPE_MULTIPLIER]: any,
 *  [battleEventEnum.CALCULATE_MISS]: any,
 *  [battleEventEnum.GET_ELIGIBLE_TARGETS]: any,
 *  [battleEventEnum.AFTER_WEATHER_SET]: any,
 *  [battleEventEnum.AFTER_TRANSFORM]: { target: BattlePokemon, beforeSpeciesId: PokemonIdEnum, afterSpeciesId: PokemonIdEnum },
 * }[K]} BattleEventArgsWithoutEventName
 */

/**
 * @template {BattleEventEnum} K
 * @typedef {BattleEventArgsWithoutEventName<K> & { eventName: K }} BattleEventArgs
 */

module.exports = {
  moveIdEnum,
  effectIdEnum,
  abilityIdEnum,
  heldItemIdEnum,
  battleEventEnum,
};
