on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - main
    paths:
      - "src/**"
      - ".github/workflows/discord-webhook.yml"
jobs:
  Discord-Notification:
    name: Discord notification
    runs-on: ubuntu-latest
    env:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}

    steps:
      - name: Discord notification
        uses: Ilshidur/action-discord@master
      - run: echo "Test secret ${{ secrets.TEST_SECRET }}"
